name: Configuration Management Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11'

      # Build and Test API
      - name: Install dependencies (API)
        run: cd api && npm ci

      - name: Build API
        run: cd api && npm run build

      - name: Test API
        run: cd api && npm run test

      # Build Frontend
      - name: Install dependencies (Frontend)
        run: cd web && npm ci

      - name: Build Frontend
        run: cd web && npm run build

  acceptance_test:
    runs-on: ubuntu-latest
    needs: commit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11'

      # Install Dependencies and Start Backend
      - name: Install dependencies (API)
        run: cd api && npm ci

      - name: Start Backend
        run: cd api && npm run dev &

      # Install Dependencies and Start Frontend
      - name: Install dependencies (Frontend)
        run: cd web && npm ci

      - name: Start Frontend
        run: cd web && npm run dev &

      # Wait for Services to Start
      - name: Wait for Backend and Frontend
        run: sleep 10

      # Run
      - name: Run Cypress Tests
        run: cd web && npx cypress run
